# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_buildHmm <- function(lengths, values, chromosomeSizes) {
    .Call('srnadiff_rcpp_buildHmm', PACKAGE = 'srnadiff', lengths, values, chromosomeSizes)
}

rcpp_viterbi <- function(chromosomeSizes, transitions, emissions, starts, counts, pvalues, lengths, values) {
    .Call('srnadiff_rcpp_viterbi', PACKAGE = 'srnadiff', chromosomeSizes, transitions, emissions, starts, counts, pvalues, lengths, values)
}

