# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute unique counts.
#'
#' @param lengths          the sizes of the RLEs (one list per chromosome)
#' @param values           the values of the RLEs (one list per chromosome)
#' @param chromosomeSizes  the sizes of the chromosomes
#' @param minDepth         minimum coverage
#' @param minSize          minimum region size
#' @param maxSize          maximum region size
#' @param minDifference    minimum difference between 2 regions
#' @return                 selected regions
rcpp_clustering <- function(lengths, values, chromosomeSizes, minDepth, minSize, maxSize, minDifference) {
    .Call('_srnadiff_rcpp_clustering', PACKAGE = 'srnadiff', lengths, values, chromosomeSizes, minDepth, minSize, maxSize, minDifference)
}

#' Compute unique counts.
#'
#' @param lengths          the sizes of the RLEs (one list per chromosome)
#' @param values           the values of the RLEs (one list per chromosome)
#' @param chromosomeSizes  the sizes of the chromosomes
#' @return                 the unique counts
rcpp_buildHmm <- function(lengths, values, chromosomeSizes) {
    .Call('_srnadiff_rcpp_buildHmm', PACKAGE = 'srnadiff', lengths, values, chromosomeSizes)
}

#' Run the Viterbi algorithm on the HMM.
#'
#' @param chromosomeSizes  the sizes of the chromosomes
#' @param transitions      the transition log-probabilities
#' @param emissions        the emission log-probabilities
#' @param starts           the start log-probabilities
#' @param counts           the unique counts
#' @param pvalues          the p-values of the counts
#' @param lengths          the sizes of the RLEs (one list per chromosome)
#' @param values           the values of the RLEs (one list per chromosome)
#' @return                 a segmentation of the chromosomes
rcpp_viterbi <- function(chromosomeSizes, transitions, emissions, starts, counts, pvalues, lengths, values) {
    .Call('_srnadiff_rcpp_viterbi', PACKAGE = 'srnadiff', chromosomeSizes, transitions, emissions, starts, counts, pvalues, lengths, values)
}

